parser: 'babel-eslint'
env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jest
rules:
  linebreak-style:
    - error
    - unix
  'no-console': 0
  'no-class-assign': 0